export interface FormationModuleData {
  id: string;
  title: string;
  personalizedFirstSlide?: boolean;
  slides: string[][];
}

export const FORMATION_MODULES: FormationModuleData[] = [
  {
    id: "societe",
    title: `La société`,
    slides: [
      [
        `Présentation de l’entreprise`,
        `Module 1`,
      ],
      [
        `Sommaire`,
        `1970`,
        `2006`,
        `2007`,
        `2018`,
        `2024`,
        `Création de la société`,
        `Introduction boursière`,
        `Expansion européenne`,
        `OVB Belgium`,
        `Aujourd’hui`,
        `Notre mission`,
      ],
      [
        `1970`,
        `N°1`,
        `service financier en Europe`,
        `Création de la société`,
        `Leader en Europe avec une présence dans 16 pays`,
        `+/- 5.000`,
        `intermédiaires financiers`,
        `55 ans`,
        `+3,7 millions de clients`,
        `Un passé fort pour un avenir solide`,
      ],
      [
        `OVB et le courtage`,
        `Nous travaillons dans le domaine des assurances sans toutefois être une compagnie d’assurance`,
        `Nos partenaires`,
        `Nos particularités`,
        `Nous ne proposons aucun contrat au nom d’OVB`,
        `Nous conseillons nos clients via de nombreuses compagnies d’assurance sur l’échelon européen`,
        `Nous assurons le service auprès de tous nos clients`,
      ],
      [
        `2006`,
        `Introduction boursière`,
        `OVB cotée en bourse`,
        `basler beteiligungsholding GmbH 33%`,
        `Signal Iduna lebenversicherung AG 32%`,
        `Signal Iduna krankenversicherung AG 21%`,
        `Generali lebenversicherung AG 11%`,
        `Freeﬂoat 3%`,
        `OVB cadre fortement l’utilisation de son image au travers de guidelines très précises`,
        `OVB est très sensible à sa réputation`,
        `notamment en relation avec la bourse`,
        `OVB veut se distinguer au niveau de la qualité offerte aux clients, raison de ses +50 ans d’expérience`,
      ],
      [
        `2007`,
        `expansion européenne`,
        `OVB s’est développée au fil des années à travers l’Europe et est aujourd’hui présente dans 16 pays différents`,
        `1970`,
        `1991`,
        `1992`,
        `1993`,
        `1995`,
        `1999`,
        `2002`,
        `2003`,
        `2007`,
        `2018`,
        `2022`,
      ],
      [
        `L’union fait la force`,
        `OVB en Belgique`,
      ],
      [
        `2018`,
        `OVB Belgium (OVB Willemot)`,
        `Les informations clés`,
        `Créé en 1841 (+180 ans d’expérience) Siège administratif à Gand`,
        `Offre globale grâce à des partenariats avec les acteurs majeurs du marché`,
        `Une équipe d’environ 180 intermédiaires financiers agréés FSMA`,
      ],
      [
        `Nos partenaires en Belgique`,
        `Des partenaires forts pour des solutions optimales`,
      ],
      [
        `Le principe du courtage`,
        `Clients`,
        `Partenaires`,
        `Un intermédiaire pour s’occuper de tout et faciliter la tâche aux clients`,
      ],
      [
        `FSMA`,
        `BNB`,
        `Assuralia`,
        `Les organismes de contrôle`,
      ],
      [
        `2024`,
        `Aujourd’hui`,
        `Voici une partie de nos représentants`,
      ],
      [
        `Le Board de direction`,
        `Mario FREIS`,
        `CEO OVB`,
        `Christian HÖFEL`,
        `CSO OVB`,
        `Gerrit Nollet`,
        `DG Willemot`,
        `Cedric Ryckaert`,
        `CFO Willemot`,
      ],
      [
        `Les coordinateurs nationaux`,
        `Dietmar Zimmer`,
        `Coordinateur`,
        `national`,
        `Jean-Noël Didrich`,
        `Coordinateur`,
        `national`,
        `Olivier Demarteau`,
        `Coordinateur`,
        `national`,
        `Soufiane Harram`,
        `Coordinateur`,
        `national`,
        `La direction commerciale`,
      ],
      [
        `Nos bureaux`,
        `Siège à Gand`,
        `Bureau à Bruxelles (Avenue Louise) Bureau à Mons (Boulevard Sainctelette)`,
        `Vision Liège, Charleroi, Namur, Anvers Bruges`,
      ],
      [
        `Notre mission`,
        `Les valeurs`,
        `Intégrité`,
        `Bienveillance`,
        `Enthousiasme`,
        `Honnêteté`,
        `Engagement`,
        `No critic`,
        `100% responsable`,
      ],
      [
        `Pourquoi êtes-vous là ?`,
        `Quel est votre rôle ?`,
        `« Actuellement, je suis en formation au sein du groupe Willemot OVB.`,
        `Mon rôle est d’améliorer votre sécurité sociale. D’une part, en vous aidant à payer moins d’impôts. Deuxièmement, en sécurisant votre avenir financier.`,
        `Et pour finir en améliorant vos protections familiales. »`,
      ],
      [
        `Votre titre chez OVB Willemot`,
        `Financial Trainee 1`,
      ],
      [
        `Prenez contact avec votre coach`,
      ],
    ],
  },
  {
    id: "opportunites",
    title: `Les opportunités`,
    slides: [
      [
        `Module 2`,
        `Opportunités`,
      ],
      [
        `Sommaire`,
        `1`,
        `2`,
        `3`,
        `4`,
        `5`,
        `6`,
        `Y a-t-il un marché ?`,
        `Système ACS`,
        `Les recommandations`,
        `L’entreprenariat`,
        `Notre programme de formation`,
        `Une carrière unique`,
        `7`,
        `Smart Fun`,
      ],
      [
        `1`,
        `Y a-t-il un marché ?`,
        `Entreprise à portée européenne expertise & expérience`,
      ],
      [
        `1`,
        `Solutions en fonction des besoins du client parmi`,
        `+100`,
        `partenaires`,
        `Entreprise à portée européenne expertise &`,
        `expérience`,
        `Protéger sa famille, sa santé, payer moins d’impôts & prévoir son avenir`,
        `Y a-t-il un marché ?`,
      ],
      [
        `1`,
        `Faisons un sondage ensemble...`,
        `Y a-t-il un marché ?`,
        `Voulez-vous payer moins d’impôts ?`,
        `Voulez-vous protéger votre famille ?`,
        `Voulez-vous être capable de prévoir votre avenir financier ?`,
      ],
      [
        `1`,
        `Y a-t-il un marché ?`,
        `Protéger sa famille`,
        `Les soins de santé sont la 2e cause d’endettement`,
        `Le coût du décès représente entre 5.000€ et 25.000€`,
        `Payer moins d’impôts`,
        `La Belgique est dans le top 3 des pays européens les plus imposés`,
        `95% de la population ignore les possibilités d’optimisation fiscale`,
        `Prévoir son avenir financier`,
        `Près de 20% des pensionnés vivent sous le seuil de pauvreté & le compte épargne coûte de l’argent`,
      ],
      [
        `1`,
        `Un peu de mathématique`,
        `En ciblant les travailleurs`,
        `Les travailleurs en 2024 représentent`,
        `5.000.000 de personnes`,
        `Prenons 10% du marché`,
        `On a donc 500.000 personnes (clients potentiels)`,
        `imaginons qu’on a 1000 clients / mois`,
        `Il faudrait 40 ans pour saturer 10% d’un marché figé`,
        `Y a-t-il un marché ?`,
        `La loi sur l’épargne pension date de 1986`,
      ],
      [
        `2`,
        `Système ACS`,
        `Un système qui fonctionne depuis plus de 50 ans`,
        `RDV 1`,
        `RDV 2`,
        `RDV 3 - 4 - ...`,
      ],
      [
        `2`,
        `Système ACS`,
        `Un système qui fonctionne depuis plus de 50 ans`,
        `Analyse`,
        `Conseil`,
        `Service`,
        `Suivi`,
      ],
      [
        `Financial Trainee 1 (FT1)`,
        `Financial Trainee 2 (FT2)`,
        `Financial Trainee 3 (FT3)`,
        `Mon rôle selon ma fonction`,
        `Stage - Cahier d’analyse`,
        `Formation agréments - cahier d’analyse`,
        `Agréments FSMA - Conseils`,
      ],
      [
        `Le cahier d’analyse`,
      ],
      [
        `Les formations (théorie + pratique)`,
      ],
      [
        `3`,
        `Les recommandations`,
        `Comprenons ce principe selon une petite analogie`,
        `Le taux horaire d’un conseiller en gestion de patrimoine est de l’ordre de 200€ de l’heure`,
        `Pour les cas les plus simples, compter 500€ pour un bilan patrimonial`,
        `les situations plus complexes coûtent`,
        `jusqu’à 5 000€!`,
        `Un service à haute valeur ajoutée`,
        `sans aucun coût pour le client`,
        `Le coût du conseil, du suivi et service est de 0 euro`,
        `LE SERVICE EST 100% gratuit en échange de recommandations (pré-accord en cahier d’analyse)`,
      ],
      [
        `3`,
        `Les recommandations`,
        `Celui qui ne conseille pas ses amis n’est pas un ami`,
      ],
      [
        `Les 3 objectifs de vos premiers rendez-vous`,
        `Formations - Role Play`,
        `Confiance - Pratique`,
      ],
      [
        `Les 3 objectifs de vos premiers rendez-vous`,
        `Formations - Role Play`,
        `Confiance - Pratique RECOMMANDATIONS`,
      ],
      [
        `La satisfaction ça se partage`,
        `8% de nos clients viennent de nos connaissances`,
        `92% de nos clients ont été recommandés`,
        `X rdv x 8 à 12 recommandations`,
      ],
      [
        `4`,
        `Temps = Argent`,
        `Employés, ouvriers, ...`,
        `Compétences = Argent`,
        `Avocats, médecins, ...`,
        `Leadership = Argent`,
        `Chefs d’entreprises`,
        `Argent = Argent`,
        `Bourse, immobiliers, ...`,
        `L’entreprenariat à 0 investissement`,
      ],
      [
        `4`,
        `Avantages`,
        `Inconvénients`,
        `L’entreprenariat à 0 investissement`,
        `L’entreprenariat chez OVB Willemot`,
        `Vous êtes votre propre patron`,
        `Vous décidez vous-mêmes de vos horaires Vous bénéficiez d’un statut fiscal avantageux Possibilité de revenus illimtés`,
        `Capital de départ nécessaire`,
        `Suivi administratifs lourds (TVA, ...) Livré à soi-même`,
        `Frais fixes`,
        `Lois sociales`,
      ],
      [
        `Un statut spécial : apporteur d’affaires`,
        `Le statut de démarrage`,
        `3 mois`,
      ],
      [
        `5`,
        `Notre programme de formation`,
        `Une formation à 360°`,
        `Développement personnel`,
        `Communication`,
        `Entreprenariat`,
        `Vente`,
        `Leadership`,
      ],
      [
        `5`,
        `Notre programme de formation`,
        `Une formation prise à 100% en charge par OVB Willemot`,
        `Communication Management situationel Prise de parole en public Gestion d’entreprise Vente et marketing Fiscalité`,
        `FSMA`,
      ],
      [
        `6`,
        `Une carrière unique`,
        `Un système qui fonctionne depuis plus de 50 ans`,
        `Evolution sur base de vos résultats`,
        `Transparence de carrière`,
        `Revenus illimités`,
      ],
      [
        `7`,
        `Mises à l’honneur`,
        `Voyages`,
        `Ipad, Apple Watch, ...`,
        `Bons d’achat`,
        `Smart Fun`,
        `Mise à l’honneur, incentives, concours, ...`,
      ],
      [
        `7`,
        `Smart Fun`,
        `Club Mont-Blanc`,
      ],
      [
        `7`,
        `Smart Fun`,
        `Croisière`,
      ],
      [
        `7`,
        `Smart Fun`,
        `Bal OVB`,
      ],
      [
        `7`,
        `Smart Fun`,
        `OVB Campus`,
      ],
      [
        `Prenez contact avec votre coach`,
      ],
    ],
  },
  {
    id: "problematiques-marche",
    title: `Les problèmes du marché`,
    slides: [
      [
        `Module 3`,
        `Les problématiques du marché`,
      ],
      [
        `Sommaire`,
        `1`,
        `2`,
        `3`,
        `4`,
        `5`,
        `6`,
        `La sécurité sociale`,
        `La pension`,
        `L’inflation`,
        `Le coût des soins de santé`,
        `Le statut “incapacité”`,
        `Le décès`,
      ],
      [
        `1`,
        `une histoire de dualité`,
        `La sécurité sociale`,
        `Travailleurs`,
        `Actifs`,
        `En bonne santé`,
        `Avec revenus`,
        `Sans enfants`,
        `Chômeurs`,
        `Pensionnés`,
        `Malades`,
        `Sans revenus`,
        `Avec enfants`,
      ],
      [
        `Prestations d’aide Absence de revenus professionnels`,
        `Revenu de remplacement Chômage, pension, incapacité de travail`,
        `Les 3 fonctions de la sécurité sociale`,
        `Supplément de revenus Allocations familiales`,
      ],
      [
        `1`,
        `Les médias en parlent`,
        `La pension`,
      ],
      [
        `1`,
        `La pension`,
        `DES CARRIÈRES DE PLUS EN PLUS COURTES, UNE POPULATION VIEILLISSANTE ET UN TAUX D'EMPLOI BAS`,
        `Avec l'allongement des études et les sorties précoces du marché du travail, la durée des carrières s'élève à 33,4 ans alors que la durée de vie est de 80,9 ans. Avec une population vieillissante (diminution du nombre de jeunes et allongement de l'espérance de vie), le ratio cotisants /pensionnés s'élève aujourd'hui à 1,8. Il ne sera plus que de 1,5 travailleur cotisant pour 1 pensionné en 2040 et continuera de chuter vers 1,3 en 2070. Ces actifs devront assurer, par leur travail, le financement des pensions de leurs aînés pour un total de 50 milliards EUR. Pour améliorer ce ratio, il n'y a qu'un moyen: améliorer le taux d'emploi des jeunes et des seniors, beaucoup trop bas en Belgique. Le taux d'emploi des 55-64 ans est parmi les plus bas, avec seulement 1 personne sur 2 en emploi dans cette tranche d'âge. La situation est pire encore à 60 ans avec seulement 1 personne sur 3 en emploi. Preuve que l'idée selon laquelle il faut écarter les seniors pour faire de la place aux jeunes ne fonctionne pas.`,
        `Source : Fédération des Entreprises Belges`,
      ],
      [
        `Taux d’emploi selon les âges`,
        `Les carrières de plus en plus courtes`,
        `Source : Fédération des Entreprises Belges`,
      ],
      [
        `Ratio actif-passif selon les années`,
        `La population est vieillissante`,
        `1960`,
        `6,3 actifs pour 1 pensionné`,
        `2020`,
        `3,3 actifs pour 1 pensionné`,
        `2060`,
        `???`,
      ],
      [
        `Pyramide des âges`,
        `La population est vieillissante`,
        `1960`,
        `2020`,
        `2060`,
      ],
      [
        `Le déficit de pension`,
        `Le déficit de pension`,
        `Pension légale`,
        `Votre dernier revenu`,
        `Votre revenu à la pension`,
        `-30 à 60%`,
        `Dernier revenu`,
        `Pension légale`,
        `Déficit de pension`,
      ],
      [
        `Fonctionnaires`,
        `Employés`,
        `Indépendant`,
        `3594 €`,
        `1836 €`,
        `1445 €`,
        `3160 €`,
        `Source : Pensionstat.be`,
        `1419 €`,
        `849 €`,
        `La pension moyenne par statut`,
      ],
      [
        `Solution - épargner`,
      ],
      [
        `3`,
        `L’inflation`,
        `La hausse généralisée des prix`,
      ],
      [
        `3`,
        `100 € épargné`,
        `100,11 €`,
        `100 € (coût de la veste)`,
        `101,40 €`,
        `L’inflation`,
        `Comprenons ce principe selon un exemple`,
        `taux d’intérêt de 0,11%`,
        `Inflation à 1,44%`,
      ],
      [
        `SOINS DE SANTÉ : LE BELGE PAYE PLUS QUE SES VOISINS`,
        `Le Belge paye, en moyenne, 17,9% des soins de santé de sa poche. Cela peut sembler raisonnable, mais c’est beaucoup plus que dans les pays voisins.`,
        `Les soins en Belgique sont relativement accessibles. On peut ainsi aller chez le généraliste en ne payant que le ticket modérateur (aussi appelé tiers payant), soit 4 euros. Néanmoins, 17,9% du montant des soins de santé restent à la charge du patient. Cette partie de la somme n’est donc ni prise en charge par la sécurité sociale ni par les assurances. C’est plus que chez les Allemands qui ne payent que 12%, les Français (8,9%) ou encore les Néerlandais (9,3%).`,
        `Les dépenses au niveau des soins de santé pour les hospitalisations et les frais ambulatoires ont augmenté de 48% en onze ans.`,
        `4`,
        `Le coût des soins de santé`,
        `https://trends.levif.be/mon-argent/soins-de-sante-le-belge-paye-plus-que-ses-voisins/`,
      ],
      [
        `Le tiers payant`,
        `2.000€`,
        `5.000€`,
        `3.000€ TOT 10.000€`,
        `6.700€ à charge de la mutuelle`,
        `3.300€ à charge du patient`,
      ],
      [
        `Sommaire`,
        `1`,
        `2`,
        `3`,
        `4`,
        `5`,
        `6`,
        `La sécurité sociale`,
        `La pension`,
        `L’inflation`,
        `Le coût des soins de santé`,
        `Le statut “incapacité”`,
        `Une carrière unique`,
      ],
      [
        `Source : Statistiques de l’INAMI - www.inami.be (2020)`,
        `*Isolé(e) : si vous habitez seul(e) ou votre partenaire gagne un revenu brut mensuel de moins de 1593,81€`,
        `*Avec charge familiale : si votre partenaire perçoit un revenu mensuel brut inférieur à 990,04€`,
        `5`,
        `Le statut “incapacité”`,
      ],
      [
        `Problématiques financières`,
        `comptes bloqués, coûts des funérailles, paiement des frais de successions,...`,
        `Problématiques administratives`,
        `Déclarer le décès, contacter les compagnies d’assurance, ...`,
        `Problématiques organisationnelles`,
        `Respect des dernières volontés, préparation des funérailles, rapatriement`,
        `Problématiques psychologiques`,
        `Une aide ou un soutien pour traverser cette épreuve est souvent utile`,
        `6`,
        `Le décès`,
      ],
      [
        `Débloquer un compte bancaire`,
      ],
      [
        `Prenez contact avec votre coach`,
      ],
    ],
  },
  {
    id: "education-financiere",
    title: `L'éducation financière`,
    slides: [
      [
        `Education financière`,
        `Module 4`,
      ],
      [
        `Sommaire`,
        `1`,
        `2`,
        `3`,
        `4`,
        `5`,
        `6`,
        `Ligne de vie`,
        `La pension`,
        `Les 4 piliers de la pension`,
        `L’inflation`,
        `Stratégie d’investissement`,
        `Les 3 règles d’investissement`,
        `7`,
        `Nos partenaires`,
      ],
      [
        `1`,
        `La vie financière`,
        `Ligne de vie`,
      ],
      [
        `Fonctionnaires`,
        `Employés`,
        `Indépendant`,
        `3594 €`,
        `1836 €`,
        `1445 €`,
        `3160 €`,
        `Source : Pensionstat.be`,
        `1419 €`,
        `849 €`,
        `2`,
        `La pension`,
      ],
      [
        `Ratio actif-passif en fonction des années`,
        `La population est vieillissante`,
        `1960`,
        `6,3 actifs pour 1 pensionné`,
        `2020`,
        `3,3 actifs pour 1 pensionné`,
        `2060`,
        `???`,
      ],
      [
        `Pyramide des âges`,
        `Les carrières de plus en plus courtes`,
        `1960`,
        `2020`,
        `2060`,
      ],
      [
        `L’importance de l’épargne`,
      ],
      [
        `Le déficit de pension`,
        `Le déficit de pension`,
        `Pension légale`,
        `Votre dernier revenu`,
        `Votre revenu à la pension`,
        `-30 à 60%`,
      ],
      [
        `Votre dernier revenu`,
        `3`,
        `Les 4 piliers de la pension`,
        `Pension légale`,
        `Votre revenu à la pension`,
        `Constituée	via	des	prélèvements	sur	le salaire, elle est versée par l’État.`,
      ],
      [
        `Votre dernier revenu`,
        `3`,
        `Les 4 piliers de la pension`,
        `Pension légale`,
        `2e Pilier`,
        `Pension complémentaire`,
        `Assurance   de   groupe   souscrite   par l’employeur ou via des dispositifs comme la Pension    Libre    Complémentaire    pour Indépendants    (PLCI)    ou    l'Engagement`,
        `Individuel	de	Pension	(EIP)	pour	les indépendants.`,
      ],
      [
        `3`,
        `Pension légale`,
        `Votre dernier revenu`,
        `Permet	de	bénéficier	d’un`,
        `les`,
        `avantage	fiscal	sur primes versées.`,
        `Les 4 piliers de la pension`,
        `2e Pilier`,
        `Pension complémentaire`,
        `3e Pilier`,
        `Plans de pension individuels fiscalement déductibles`,
      ],
      [
        `Pension légale`,
        `Votre dernier revenu`,
        `3`,
        `Les 4 piliers de la pension`,
        `2e Pilier`,
        `Pension complémentaire`,
        `3e Pilier`,
        `Plans de pension individuels fiscalement déductibles`,
        `Non éligible à une réduction d'impôt,  cette  épargne  est basée  sur  des  initiatives personnelles.`,
        `4e Pilier`,
        `Epargne personnelle`,
      ],
      [
        `4`,
        `L’inflation`,
        `On parle d’inflation lorsqu’il y a une hausse généralisée des prix, et non pas seulement de certains produits. Il en résulte que vous pouvez acheter moins de	biens et de services pour un euro.`,
        `Inversement, un euro vaut moins qu’avant.`,
      ],
      [
        `4`,
        `L’inflation`,
        `L’inflation moyenne est estimée à 3,02% en 2024`,
      ],
      [
        `4`,
        `Combattre l’inflation`,
        `Inflation`,
        `3,2%`,
        `Trouver   une   manière   de faire travailler l’argent pour que  ça  rapporte  plus  que 3,2% (l’inflation)`,
      ],
      [
        `4`,
        `Combattre l’inflation`,
        `Où se situe le compte épargne sur ce graphique ?`,
        `Inflation`,
        `3,2%`,
      ],
      [
        `4`,
        `Combattre l’inflation`,
        `Où se situe le compte épargne sur ce graphique ?`,
        `3,2%`,
        `Le compte épargne rapporte environ 0,15%`,
      ],
      [
        `4`,
        `Combattre l’inflation`,
        `Où se situe le compte épargne sur ce graphique ?`,
        `3,2%`,
        `Le compte épargne`,
      ],
      [
        `Sommaire`,
        `1`,
        `2`,
        `3`,
        `4`,
        `5`,
        `6`,
        `Ligne de vie`,
        `La pension`,
        `Les 4 piliers de la pension`,
        `L’inflation`,
        `Stratégies d’investissement`,
        `Les 3 règles d’investissement`,
        `7`,
        `Nos partenaires`,
      ],
      [
        `5`,
        `Les stratégies d’investissement`,
        `Sécurité ou prise risque ?`,
        `BRANCHE 21`,
        `BRANCHE 23`,
      ],
      [
        `La branche 21`,
        `Plutôt sécurité...`,
        `Une assurance de la branche 21 (fond en euro) vous offre un taux d’intérêt garanti, avec éventuellement une participation bénéficiaire en plus. Le taux d’intérêt garanti est d’application pour chaque versement séparé. La participation bénéficiaire n'est pas garantie : elle dépend des résultats de l'assureur. Le taux d’intérêt garanti se situe actuellement chez la plupart des assureurs entre 0,1 et 1,25%`,
        `Intérêt garanti`,
        `Intérêts généralement faibles Garantie d’Etat jusqu’à 100.000€`,
      ],
      [
        `Où se situe la branche 21 sur le graphique ?`,
        `La branche 21`,
        `Inflation`,
        `3,2%`,
      ],
      [
        `Où se situe la branche 21 sur le graphique ?`,
        `La branche 21`,
        `3,2%`,
        `Branche 21`,
      ],
      [
        `Emprunter aux particuliers`,
        `Les assurances-vie branche 21 sont des placements sûrs, parce que les assureurs qui les proposent doivent investir avec prudence. Elles sont en outre couvertes par un système de garantie.`,
        `En effet, chaque contrat d'assurance-vie de la branche 21 bénéficie de la protection du Fonds de garantie. Si un assureur belge fait faillite, le Fonds fait en sorte que l'assuré récupère son argent.`,
        `Cette garantie vaut jusqu'à un montant maximum de 100 000 euros par preneur d'assurance et par entreprise d'assurance, pour tous vos contrats d'assurance-vie branche 21 réunis.`,
        `Si vous avez plusieurs contrats d'assurance-vie branche 21 auprès d'un assureur, qui fait faillite, le Fonds de garantie intervient pour maximum 100 000 euros. Pour un complément d'information, voir le site du Fonds de garantie.`,
        `Qu’est-ce que la garantie d’Etat ?`,
      ],
      [
        `Emprunter aux particuliers`,
        `Qu’est-ce que la garantie d’Etat ?`,
      ],
      [
        `La branche 23`,
        `Plutôt prise de risques`,
        `Pour une solution de la branche 23 (unité de compte), il n’est jamais question d’un taux d’intérêt garanti. Le rendement dépend en effet du ou des fonds de placement au(x)quel(s) cette police est liée.`,
        `Si ces fonds remportent de bons résultats, vous pouvez en tirer un bon rendement. Mais dans le cas contraire, vous risquez de perdre une partie du capital investi.`,
        `Rendement non garanti Rendement potentiellement élevé Pas de garantie d’Etat`,
      ],
      [
        `La branche 23`,
        `Plutôt prise de risques`,
        `La branche 23 peut-être constituée :`,
        `D’obligations`,
        `De fonds d’obligations D’actions`,
        `De fonds d’actions ETF`,
      ],
      [
        `Qu’est-ce qu’une obligation ?`,
        `Emprunter aux particuliers`,
        `Une obligation est un instrument financier qui représente une dette contractée par une entité (gouvernement, entreprise, collectivité locale) auprès d'investisseurs. En d'autres termes, c'est un emprunt émis par une organisation en échange de liquidités.`,
        `Comment ça fonctionne ?`,
        `Un émetteur (ex. État, entreprise) lève des fonds en vendant des obligations aux investisseurs. L’émetteur s’engage à rembourser le capital investi à une date fixée`,
        `En échange du prêt accordé par l'investisseur, l’émetteur verse des intérêts (appelés coupon) à intervalle régulier (annuel, semestriel, trimestriel).`,
        `À l’échéance, l'investisseur récupère son capital initial.`,
      ],
      [
        `La branche 23`,
        `Plutôt prise de risques`,
        `La branche 23 peut-être constituée : D’obligations`,
        `De fonds d’obligations`,
        `D’actions`,
        `De fonds d’actions ETF`,
      ],
      [
        `Qu’est-ce qu’un fonds d’obligations ?`,
        `Emprunter aux particuliers`,
        `Un fonds d’obligations est un type de fonds d’investissement composé principalement d’obligations (titres de dette émis par des entreprises, des États ou d’autres institutions). Il permet aux investisseurs d’accéder à un portefeuille diversifié d’obligations sans avoir à acheter directement ces titres un par un.`,
        `Comment ça fonctionne ?`,
        `Gestion par une société d’investissement : Le fonds est géré par des professionnels qui sélectionnent et achètent des obligations selon une stratégie définie.`,
        `Diversification : Le portefeuille contient plusieurs obligations, ce qui réduit le risque lié à un seul émetteur. Rendements via les coupons : Le fonds perçoit les intérêts (coupons) des obligations et peut les redistribuer aux investisseurs sous forme de dividendes ou les réinvestir.`,
        `La valeur du fonds évolue en fonction des taux d’intérêt, de la qualité des obligations et des conditions du marché.`,
      ],
      [
        `Qu’est-ce qu’une action ?`,
        `L’investissement`,
        `Une action représente une fraction du capital d'une entreprise. Si vous détenez des actions, vous êtes propriétaire d'une partie de la société. Cela vous donne des droits, notamment, celui de recevoir des dividendes, si la société en distribue, et d'influer sur la politique générale de l'entreprise lors des assemblées générales d'actionnaires.`,
        `Comment ça fonctionne ?`,
        `Une entreprise émet des actions pour lever des fonds (introduction en bourse ou augmentation de capital). Les actions s’échangent sur des marchés financiers comme Euronext, le NYSE ou le Nasdaq.`,
        `Certaines entreprises distribuent une partie de leurs bénéfices aux actionnaires sous forme de dividendes. Le prix de l’action évolue selon l’offre et la demande, les résultats de l’entreprise et le marché.`,
      ],
      [
        `La branche 23`,
        `Plutôt prise de risques`,
        `La branche 23 peut-être constituée : D’obligations`,
        `De fonds d’obligations D’actions`,
        `De fonds d’actions`,
        `ETF`,
      ],
      [
        `Qu’est-ce qu’un fonds d’action ?`,
        `L’investissement`,
        `Un fonds d’actions est un type de fonds d’investissement qui regroupe un portefeuille diversifié d’actions de plusieurs entreprises. Il permet aux investisseurs d’accéder à un panier d’actions géré par des professionnels, sans avoir à acheter individuellement chaque titre.`,
        `Comment ça fonctionne ?`,
        `Les investisseurs placent leur argent dans un fonds qui achète plusieurs actions. Un gestionnaire de fonds choisit les actions selon une stratégie définie.`,
        `Le fonds détient des actions de plusieurs entreprises, réduisant ainsi le risque.`,
        `Si les actions du fonds prennent de la valeur, la valeur des parts du fonds augmente. Certains fonds distribuent des dividendes si les entreprises du portefeuille en versent.`,
      ],
      [
        `Qu’est-ce qu’un ETF ?`,
        `L’investissement`,
        `Un ETF (ou tracker) est un fonds d’investissement coté en Bourse qui réplique la performance d’un indice boursier, d’un secteur ou d’un actif spécifique. C’est un moyen simple et efficace d’investir sur les marchés financiers avec des frais réduits et une diversification immédiate.`,
        `Comment ça fonctionne ?`,
        `Un ETF suit un indice : Il investit dans les mêmes actions (ou obligations) que l’indice qu’il réplique (ex. S&P 500, CAC 40, MSCI World).`,
        `Il est coté en Bourse : Contrairement aux fonds classiques, un ETF s’achète et se vend comme une action sur le marché.`,
        `Performance indexée : Si l’indice progresse de +10%, l’ETF suit la même évolution.`,
        `Frais réduits : Comme il est souvent géré de manière passive, les frais de gestion sont plus bas qu’un fonds d’investissement classique.`,
      ],
      [
        `L’investissement`,
        `Investir dans le MSCI World Index est un des placements le plus diversifié que vous pouvez trouver. Le cours du MSCI World Index est déterminé par le cours de 1.651 actions de pays occidentaux. Les actions qui figurent sur cet indice proviennent des pays suivants : Etats-Unis, Canada, Autriche, Belgique, Danemark, Espagne, Finlande, France, Allemagne, Irlande, Israël, Italie, Pays-Bas, Norvège, Portugal, Suède, Suisse, Royaume-Uni, Australie, Hong Kong, Japon, Nouvelle-Zélande, Singapour.`,
        `C'est la société Morgan Stanley Capital International (MSCI) qui compose l'indice. L'indice a été lancé à 100 points en 1969. Le cours actuel se situe aux alentours de 2.000 points.`,
        `Qu’est-ce que le MSCI World Index ?`,
      ],
      [
        `de 1969 à 2020`,
        `Le MSCI World`,
      ],
      [
        `Où situer les fonds d’obligations, les fonds mixtes (obligations-actions, les fonds d’actions et les ETF sur le graphique ?`,
        `La branche 23`,
        `3,2%`,
        `Branche 21`,
      ],
      [
        `Où situer les fonds d’obligations, les fonds mixtes (obligations-actions, les fonds d’actions et les ETF sur le graphique ?`,
        `La branche 23`,
        `3,2%`,
        `Fonds mixtes (obligations-actions)`,
        `Fonds d’obligations`,
        `Fonds d’action - ETF`,
      ],
      [
        `Les degrés de risque`,
        `Sécurité ou prise risque ?`,
        `BRANCHE 21	Fonds d’obligations`,
        `Fonds d’action`,
      ],
      [
        `L’idéal serait...`,
        `Le meilleur des deux mondes`,
        `BRANCHE 21 + 23`,
        `Intérêt garanti`,
        `Rendement potentiellement élevé Garantie d’Etat jusqu’à 100.000€`,
      ],
      [
        `6`,
        `Investir de manière périodique`,
        `Les 3 règles d’investissement`,
        `Diversifier ses investissements`,
        `Respecter le facteur temps`,
      ],
      [
        `règle 1`,
        `Diversifier ses investissements`,
        `Action`,
        `Fond d’action`,
      ],
      [
        `Respecter le facteur temps`,
        `règle 2`,
      ],
      [
        `500€`,
        `règle 3`,
        `500€`,
        `Investir de manière périodique`,
        `5€`,
        `5€`,
        `100`,
      ],
      [
        `règle 3`,
        `Investir de manière périodique`,
        `5€`,
        `2,5€`,
        `7,5€`,
        `20`,
        `13`,
        `20`,
        `40`,
        `20`,
        `+ 50%`,
        `-50%`,
        `113`,
        `5 x 100€`,
      ],
      [
        `Investir de manière périodique`,
        `500€`,
        `règle 3`,
        `5€`,
        `Prime unique`,
        `100`,
        `5 x 100€`,
        `113`,
        `5€`,
        `Prime périodique`,
      ],
      [
        `Des partenaires forts pour des solutions optimales`,
        `7`,
        `Nos partenaires en Belgique`,
      ],
      [
        `Notre partenaire AXA`,
        `Un produit d'assurance-vie d'AXA Belgium S.A. qui se compose d'une assurance-vie de la branche 21 avec un intérêt garanti par la compagnie d'assurances et/ou d'une assurance-vie de la branche 23 avec un rendement lié à différents fonds de placement internes, ainsi que de différentes garanties (optionnelles)`,
        `Une flexibilité maximale via un volet secure - lié à l'épargne branche 21 et /ou d'un volet invest lié à la branche 23`,
        `Un accès a un ou plusieurs fonds de la gamme pension plan. Vous avez la possibilité d'investir dans des fonds pouvant offrir de belles perspectives de rendement.`,
        `Des protections (optionnelles) pour vous et votre famille via certaines assurances optionnel les comme le décès par accident, l'incapacité de travail ou la perte d'emploi`,
      ],
      [
        `Notre partenaire AG`,
        `Un produit d'assurance-vie qui se compose d'une assurance-vie de la branche 21 avec un intérêt garanti par la compagnie d'assurances et/ou d'une assurance-vie de la branche 23 avec un rendement lié à différents fonds de placement internes, ainsi que de différentes garanties (optionnelles) - Pour les produits du 3e et 4e piliers de la pension`,
        `Pension légale`,
        `2e Pilier`,
        `PLCI - EIP - CPTI`,
        `Un produit d'assurance-vie qui se compose d'une assurance-vie de la branche 21 avec un intérêt garanti par la compagnie d'assurances ainsi que de différentes garanties (optionnelles) - Pour les produits du 2e pilier de la pension`,
      ],
      [
        `Notre partenaire Vivium`,
        `Un produit d'assurance-vie qui se compose d'une assurance-vie de la branche 21 avec un intérêt garanti par la compagnie d'assurances et/ou d'une assurance-vie de la branche 23 avec un rendement lié à différents fonds de placement internes, ainsi que de différentes garanties (optionnelles) - Pour les produits du 2e, 3e et 4e piliers de la pension`,
      ],
      [
        `Prenez contact avec votre coach`,
      ],
    ],
  },
  {
    id: "potentiel",
    title: `Le potentiel`,
    slides: [
      [
        `Module 5`,
        `Le potentiel`,
      ],
      [
        `Sommaire`,
        `1`,
        `2`,
        `3`,
        `Le triangle du succès`,
        `Le potentiel c’est quoi ?`,
        `Trier son potentiel`,
      ],
      [
        `1`,
        `Le triangle du succès`,
        `Potentiel`,
        `Appels`,
        `RDV`,
      ],
      [
        `1`,
        `Le triangle du succès`,
        `Potentiel/ Recommandations`,
        `Appels`,
        `RDV`,
      ],
      [
        `2`,
        `Ton carnet d’adresse`,
        `Le potentiel c’est quoi ?`,
        `Ton essence`,
        `Ton objectif prinicipal`,
      ],
      [
        `3`,
        `Trier son potentiel`,
        `Munis-toi	de	ton	téléphone	et	va	dans	ta	liste	de	contacts.	Tu sépareras cette liste en 2 colonnes (2 feuilles excel)`,
        `“ TRAVAILLENT ”`,
        `Dans cette colonne tu noteras toutes les personnes de ton répertoire qui travaillent et qui sont domiciliées en Belgique. Ne laisse personne sur le côté ! (job étudiant ne comptant pas).`,
        `“ TRAVAILLENT PAS ”`,
        `Dans cette colonne tu noteras toutes les personnes qui ne travaillent pas (ainsi que ceux qui sont en job étudiant), c'est-à-dire les étudiants, les demandeurs d'emplois, les personnes en incapacité/invalidité, ...`,
      ],
      [
        `Tu détailleras cette liste afin de répertorier un maximum d'information pour chaque contact : prénom, nom, n° GSM, âge, profession, région, situation familiale.`,
        `Exemple : Chris Vanelst — 0472/90.87.73 — 27 ans — Chauffagiste — Namur — Marié, 1 enfant, 2 frères`,
      ],
      [
        `Le réseau chaud`,
        `Ton réseau chaud est constitué par les personnes les plus proches de toi ! Ce sont des personnes qui accepteront de te voir après un simple "Viens on se voit".`,
        `Ce réseau chaud sera constitué des 15 personnes les plus proches de toi, que tu appelleras en premier lieu afin de réaliser tes premiers rendez-vous avec ces personnes.`,
        `Surligne ces personnes en jaune afin de les mettre en évidence.`,
      ],
      [
        `Prenez contact avec votre coach`,
      ],
    ],
  },
  {
    id: "appel-telephonique",
    title: `L'appel téléphonique`,
    slides: [
      [
        `Appel téléphonique`,
        `Module 6`,
      ],
      [
        `Sommaire`,
        `1`,
        `2`,
        `3`,
        `Le triangle du succès`,
        `Les 5 étapes de l’appel téléphonique`,
        `Fil rouge`,
        `4`,
        `Argumentation`,
      ],
      [
        `1`,
        `Le triangle du succès`,
        `Potentiel/ Recommandations`,
        `Appels`,
        `RDV`,
      ],
      [
        `2`,
        `Les 5 étapes de l’appel téléphonique`,
        `Important de respecter chaque étape`,
        `Fixer le rendez-vous`,
        `Présence du conjoint/ personne décisionnaire`,
        `Présence du formateur`,
        `Prendre l’adresse`,
        `Clôturer la prise de rendez-vous`,
      ],
      [
        `Fixer le rendez-vous`,
        `“Allo! C’est ... à l’appareil, bonjour !” – “Bonjour” “Comment vas-tu ?” – “Je vais bien et toi ?”`,
        `“Ecoute, je vais super bien ! Pas à me plaindre” (être énergétique et enthousiaste)`,
        `(Quelques banalités - prendre des nouvelles - demander comment vas la famille - terminer par le boulot) “Dis moi, comment va la famille ? Tout le monde se porte bien ?” - “Oui tout le monde va bien... et chez toi ? ” “Chez moi aussi tout le monde se porte bien.” (Réponse au choix)`,
        `“Et du coup le boulot ça se passe comment ? ” - “Rien de spécial, toujours la même routine et de ton côté ?”`,
        `3`,
        `Fil rouge`,
      ],
      [
        `“Justement en parlant de ça, je viens de débuter une nouvelle formation dans le secteur des finances et je voudrais avoir ton avis.”`,
        `“Quand est-ce que l’on peut se voir ?” (Donner alternative)`,
        `“Jour X ou Jour Y ?” “En matinée ou en soirée ?” “Heure X ou heure Y”`,
        `3`,
        `Fil rouge`,
        `Fixer le rendez-vous`,
      ],
      [
        `Insister sur la présence du conjoint / de la personne décisionnaire`,
        `“Au fait, au plus j’ai d’avis au mieux c’est ! Ce serait donc bien que ton/ta conjoint(e) soit là ! Surtout que ce sont des informations qui concernent le ménage.”`,
        `“Oui il/elle sera là.” – “Super!”`,
        `“Non il/elle ne sera pas disponible.” – “Ok, vu que ce sont des informations qui concernent le ménage, je préfère mettre une moment où il/elle sera là, et donc quand penses-tu que cela peut se faire ?”`,
        `“Jour X ou Jour Y ?” “En matinée ou en soirée?”`,
        `3`,
        `Fil rouge`,
      ],
      [
        `Prévenir la présence du formateur`,
        `“Je tiens aussi à t’informer que je serai accompagné de mon formateur, je suppose que ça ira pour toi ?” “Oui il n’y a aucun soucis” – “Super!”`,
        `Si l’interlocuteur ne préfère pas avoir la présence du formateur :`,
        `“Je préfère que l’on se voit à deux ! ” – “Ok je peux comprendre, mais vu que je suis en période de formation c’est super important qu’il soit là. C’est pour me former et m’améliorer. Je te rassure il est super sympa. C’est ok pour toi?”`,
        `“Ok je comprends. C’est ok” – “Ok je bloque ça dans l’agenda.”`,
        `3`,
        `Fil rouge`,
      ],
      [
        `Prendre l’adresse (mail)`,
        `Si rendez-vous en présentiel`,
        `“Au niveau de l’adresse, tu habites toujours au même endroit ?” “Oui en effet.”`,
        `“Ok, peux-tu m’épeler le nom de la rue comme ça je pourrai la noter dans le GPS. C’est rue de....”`,
        `Alternative pour un rendez-vous via Zoom`,
        `“Au niveau de ton adresse email, peux-tu me l’épeler comme ça je peux déjà l’enregistrer dans mes notes ?”`,
        `“Oui, c’est....”`,
        `3`,
        `Fil rouge`,
      ],
      [
        `Clôturer la prise de rendez-vous`,
        `“Super, je t’invite à noter notre rendez-vous dans ton agenda. Nous avons donc rendez-vous : ‘jour X’`,
        `à ‘heure X’`,
        `à ‘Adresse X’ ” / sur Zoom” “Je compte vraiment sur toi !”`,
        `“ Bonne soirée/Bonne journée”`,
        `3`,
        `Fil rouge`,
      ],
      [
        `“Je n’ai pas très bien compris. Tu suis une formation en quoi ?”`,
        `“Je suis une formation dans le secteur financier et mon rôle est de conseiller les personnes par rapport aux problématiques liées aux 4 piliers de la sécurité sociale. Et j’aurai donc besoin de ton avis par rapport à ça.`,
        `De plus, les informations que je vais t’apporter te permettront de payer moins d’impôts et d’améliorer tes protections familiales.`,
        `Mais retiens une chose, c’est surtout pour ma formation. Du coup, quand est-ce que tu es disponible ?”`,
        `4`,
        `Argumentation`,
      ],
      [
        `“Mais pourquoi moi ? Je ne m’y connais pas du tout (ou autre excuse)”`,
        `“Justement c’est idéal. Tu es exactement le profil qu’il me faut pour ma formation. Le but c’est que je puisse voir un maximum de profils différents afin d’approfondir ma formation.`,
        `Du coup, quand est-ce que tu es disponible ?”`,
        `4`,
        `Argumentation`,
      ],
      [
        `“Tu veux me vendre quelque chose, je ne suis pas intéressé.”`,
        `“Ecoute, je te rassure je ne te vendrais rien du tout! Si je veux te voir c’est dans le cadre de ma formation et j’ai besoin de ton avis.`,
        `En plus, cela me rendrait vraiment service. Alors, quand est-ce qu’on peut se voir ?”`,
        `4`,
        `Argumentation`,
      ],
      [
        `“Je suis déjà client(e) chez OVB en épargne pension”`,
        `“Ah c’est génial et bien ce serait vraiment intéressant que l’on se rencontre dans le cadre de ma formation du coup afin que je puisse avoir ton avis par rapport à nos services.`,
        `Tu pourras par la même occasion me conseiller sur les points à améliorer.”`,
        `4`,
        `Argumentation`,
      ],
      [
        `“J’ai déjà un courtier qui me conseille” / “J’ai déjà tout à ma banque”`,
        `“Et bien c’est parfait ! Je pourrais ainsi faire des comparaisons et cela m’aidera énormément pour ma formation.`,
        `De plus, je suppose que tu veux ce qu’il y a de mieux pour toi ? Du coup quand est-ce que l’on peut se voir ? Jour X ou Y ?”`,
        `4`,
        `Argumentation`,
      ],
      [
        `“Je n’ai pas le temps !”`,
        `“Justement, c’est pour ça que je t’appelle d’abord car je sais que tu es occupé. Le but n’est pas de tout t’expliquer maintenant, mais de fixer un rendez-vous ensemble et de le mettre dans ton agenda à un moment où tu es disponible.`,
        `Je te rassure ça ne prendra que 30 minutes. Tu as quand même 30 minutes pour moi ? (ton de la rigolade) Du coup, quel jour te conviendrait ?”`,
        `4`,
        `Argumentation`,
      ],
      [
        `Prenez contact avec votre coach`,
      ],
    ],
  },
  {
    id: "entretien-analyse",
    title: `L'entretien d'analyse`,
    personalizedFirstSlide: true,
    slides: [
      [
        `Arrivée d’OVB en Belgique`,
        `Qui est Willemot OVB?`,
        `1841`,
        `1970`,
        `2018`,
        `Création du courtier Willemot`,
        `Création d’OVB Holding à Cologne`,
        `+180 ans d’expérience`,
        `FSMA-BNB-ASSURALIA`,
        `Travaille avec les leaders du marché finance/assurance belge`,
        `Présent dans 16 pays`,
        `Plus de 100 partenaires`,
        `Côté en bourse`,
        `Willemot devient membre du groupe OVB`,
      ],
      [
        `LEADER SUR 16 MARCHÉS EUROPÉENS`,
        `1970`,
        `Création`,
        `d’OVB Allemagne`,
        `1991`,
        `OVB Autriche`,
        `1992`,
        `OVB Pologne`,
        `OVB R.Tchèque`,
        `OVB Hongrie`,
        `1993`,
        `OVB Grèce OVB Slovaquie`,
        `1995`,
        `Acquisition`,
        `Fidicon Suisse`,
        `1991`,
        `OVB Croatie`,
        `2002`,
        `OVB Italie`,
        `OVB Roumanie`,
        `OVB Espagne`,
        `2003`,
        `OVB France`,
        `2007`,
        `OVB Ukraine`,
        `2018`,
        `Acquisition de Willemot en Belgique`,
        `2022`,
        `OVB Slovénie`,
      ],
      [
        `Des partenaires forts`,
        `Je serais votre personne de contact et de référence pour le domaine finance/assurance,`,
        `si nous sommes amené à collaborer ensemble`,
        `Voici en quoi consiste mon travail :`,
      ],
      [
        `ANALYSE`,
        `individualisée de vos objectifs et de  vos  besoins  en  prenant  en compte votre situation familiale et ﬁnancière.`,
        `SERVICE`,
        `des entretiens de suivi réguliers pour intégrer des besoins ou des objectifs nouveaux et pour vous informer des nouvelles opportunités du marché.`,
        `CONSEIL`,
        `sur base d’une étude détaillée et personnalisée, élaboration d’un conseil global sur les principales thématiques,`,
        `avec les meilleures offres de nos partenaires`,
        `LE SYSTÈME ACS DEPUIS PLUS DE 50 ANS !`,
        `RECOMMANDATIONS`,
      ],
      [
        `Parlez-moi de votre situation actuelle !`,
        `SITUATION FAMILIALE`,
        `SITUATION PROFESSIONNELLE`,
        `SITUATION D’ÉPARGNE`,
        `Célibataire Cohabitation légale Marié`,
        `Divorcé`,
        `Des enfants ? Âge ?`,
        `Des frères et soeurs en BE ? Des cousins et cousines en BE ?`,
        `Employé Ouvrier Fonctionnaire Indépendant Au chômage`,
        `En incapacité de travail`,
        `Epargne pension Epargne Long terme`,
        `Assurance obsèques / héritage Epargne projet / Placement Epargne enfant`,
        `Épargnez-vous actuellement tous les mois ?`,
        `Si oui, combien parvenez-vous à épargner habituellement ?`,
      ],
      [
        `ANALYSE DE VOS SOLUTIONS ACTUELLES`,
        `ÉTUDIANT(E)`,
        `SALARIÉ(E) / FONCTIONNAIRE`,
        `INDÉPENDANT(E)`,
        `+297€ d’impôts`,
        `Couverture obsèques`,
        `Épargne pension`,
        `Épargne à long terme`,
        `Placement`,
        `Couverture obsèques`,
        `Épargne pension`,
        `Épargne à long terme`,
        `Placement`,
        `PLCI / EIP`,
        `Contrat INAMI`,
        `Couverture obsèques`,
        `Épargne enfant(s)`,
        `Épargne enfant(s)`,
      ],
      [
        `Analysons votre situation !`,
        `Qu’est-ce qui est le plus important pour vous aujourd’hui ?`,
        `Qu’est-ce qui vous inquiète le plus concernant l’avenir ? Qu’est-ce qui vous a motivé à accepter ce rendez-vous ?`,
      ],
      [
        `Savez-vous ce qui se passe au niveau du salaire lorsqu’on arrive à la retraite ?`,
        `€`,
        `9`,
        `Fonctionnaire : -30%`,
        `Salariés et Indépendants : -50% à -70%`,
        `67`,
        `25`,
        `« Nous vivons en moyenne 20 à 25 ans après l’âge de la retraite »`,
      ],
      [
        `LA RETRAITE`,
      ],
      [
        `LES AVANTAGES FISCAUX`,
        `Épargne Pension`,
        `Epargne à Long Terme`,
        `2 500€`,
        `(210€)`,
        `30%`,
        `Déductible`,
        `Minimum 30€/mois`,
        `SALARIÉ / INDÉPENDANT / FONCTIONNAIRE`,
        `+ 735 € d’impôts`,
        `+297€ d’impôts`,
        `1.050€`,
        `(87,5€)`,
        `30%`,
        `Déductible`,
        `+ 315 € d’impôts`,
        `Minimum 30€/mois`,
        `Garantie décès toutes causes`,
        `Capital : minimum 15.000€`,
        `Rentabilité intéressante`,
        `5 %`,
        `SIMULATION du rendement`,
        `SIMULATION de l’avantage fiscale`,
      ],
      [
        `INDÉPENDANT(e)S`,
        `LES AVANTAGES FISCAUX`,
        `PLCI`,
        `EIP`,
        `Règle des 80%`,
        `Minimum 100€/mois`,
        `100%`,
        `Déductible`,
        `INDÉPENDANT en personne physique et en société`,
        `INDÉPENDANT en SOCIÉTÉ`,
        `100%`,
        `Déductible`,
        `4004€`,
        `333€/M`,
        `Minimum 500€/an`,
      ],
      [
        `DOMAINE MÉDICAL`,
        `Contrat INAMI`,
        `Épargne GRATUITE destinée à certaines professions du domaine médical`,
        `Clique ICI`,
        `Médecins/pharmaciens-biologistes`,
        `Dentistes`,
        `Pharmaciens`,
        `Kinésithérapeutes`,
        `Logopèdes`,
        `Infirmiers indépendants`,
        `Sage-femmes`,
      ],
      [
        `Avez-vous entendu parler de l’inflation ?`,
        `Taux d’inflation moyen en Belgique = 3%`,
        `Exemple`,
        `En laissant votre épargne sur votre compte en banque,`,
        `Votre argent perd sa valeur .. et vous perdez votre pouvoir d’achat de 3%`,
        `Dans votre compte en banque :`,
        `100€/mois sur une durée de 10 ans = 12.000€ - 3% = valeur net = 11.640€`,
        `Dans un compte PLACEMENT :`,
        `3,58% cumuler + 12.000€ = 14.600€`,
        `Votre argent aura PERDU`,
        `360€ de valeur`,
        `Vous aurez GAGNÉ 2600€`,
      ],
      [
        `PLACEMENT`,
        `SIMULATION du rendement`,
        `En moyenne 3,58% de rentabilité annuelle`,
        `Durée minimum = 10 ans`,
        `Pour faire FRUCTIFIER votre argent et préparer un PROJET`,
      ],
      [
        `SÉCURISEZ VOS PROCHES`,
        `Est-ce important pour vous de sécuriser vos proches si vous n’êtes plus là ?`,
        `Avez-vous déjà mis en place une solution pour cela ?`,
      ],
      [
        `LE DÉCÈS QUELLES CONSÉQUENCES ?`,
        `LE FINANCIER, MAIS PAS QUE …`,
        `LE DÉCÈS COÛTE DE PLUS EN PLUS CHER`,
        `OUI	NON`,
        `Avez-vous perdu une personne de votre entourage proche ou éloigné ?`,
        `Si vous êtes amené à disparaitre, qui seraient les plus affectés ﬁnancièrement dans votre famille ?`,
        `Possèdent-ils une épargne aﬁn de couvrir vos obsèques, frais de succession ainsi que tous les frais annexes ?`,
        `UN DÉCÈS COÛTE ENTRE	7.000 ET 12.000 €`,
      ],
      [
        `LES CONTRAINTES LIÉS À UN DÉCÈS`,
        `•`,
        `•`,
        `•`,
        `•`,
        `Comptes bloqués`,
        `Coût des funérailles`,
        `Paiement des frais de succession`,
        `•`,
        `•`,
        `•`,
        `Etc …`,
        `Respect des dernières volontés`,
        `Préparation	des	funérailles Rapatriement  Expatriement  Etc`,
        `•`,
        `•`,
        `•`,
        `…`,
        `•`,
        `Une aide psychologique`,
        `Un soutien moral`,
        `Le deuil`,
        `Etc …`,
        `Déclarer le décès`,
        `Contacter les compagnies d’assurances`,
        `Faire débloquer les comptes`,
        `•`,
        `•`,
        `•`,
        `Déposer une déclaration de succession`,
        `Demander allocations de transition`,
        `•`,
        `•`,
        `Couper les différents abonnements`,
        `Etc …`,
        `Contraintes`,
        `Financières`,
        `Contraintes`,
        `Organisationelles`,
        `Contraintes`,
        `Emotionnelles`,
        `Contraintes`,
        `Administratives`,
      ],
      [
        `ÉPARGNE`,
        `FAMILLE / AMI(E)S`,
        `BANQUE`,
        `DÉCÈS : VERS QUI SE DIRIGER ?`,
        `Les 3 options les plus courantes…`,
        `Trouvez-vous aujourd’hui normal de faire un crédit pour un décès ?`,
        `Aimeriez-vous découvrir la solution qui s’offre à vous pour cela ?`,
      ],
      [
        `L’Assurance obsèques`,
        `Aimeriez-vous connaitre la mensualité par rapport à votre âge ?`,
        `SIMULATION`,
      ],
      [
        `L’Assurance héritage`,
        `Aimeriez-vous connaitre la mensualité par rapport à votre âge ?`,
        `SIMULATION`,
      ],
      [
        `L’AVENIR DE VOS ENFANTS`,
      ],
      [
        `Pour quels types de projet épargner pour son enfant ?`,
        `Etudes universitaires`,
        `Premier bien immobilier`,
        `Capital de départ vie active`,
      ],
      [
        `La meilleure solution en Belgique`,
        `Cade au de l’état = ALLOCATIONS FAMILIALES = 150€/mois`,
        `Montant minimum = 50€/mois`,
        `Rentabilité annuelle = 5% en moyenne`,
        `Capital héritage en cas de décès = 15.000€`,
        `Parent titulaire du compte du début jusqu’à la fin du contrat`,
        `SIMULATION`,
      ],
      [
        `1 accès à nous 7/7j.`,
        `1 LIVRE ( digital ) OFFERT sur l’épargne et la prévoyance en Belgique.`,
        `“Résumé de ce rendez-vous”`,
        `1 ASSISTANCE OFFERTE tous`,
        `les ans pour le remplissage de votre déclaration d’impôts.`,
        `“pour salariés”`,
        `1 accès GRATUIT à tout notre réseau d’experts ﬁnanciers :`,
        `-Courtier en crédit personnel`,
        `-Courtier en crédit hypothécaire`,
        `-Courtier en assurance non-vie`,
        `1`,
        `2`,
        `3`,
        `4`,
        `LES CADEAUX`,
        `QUE NOUS OFFRONS À NOS CLIENTS :`,
      ],
      [
        `D’AUTRES QUESTIONS ?`,
      ],
      [
        `ETUDIANT(E)`,
        `SALARIÉ(E) FONCTIONNAIRE`,
        `INDÉPENDANT(E)`,
        `COUVERTURE`,
        `ÉPARGNE`,
        `ÉPARGNE`,
        `ÉPARGNE`,
        `ÉPARGNE`,
        `PLCI`,
        `CONTRAT`,
        `OBSÈQUES`,
        `PENSION`,
        `LONG TERME`,
        `PROJET`,
        `ENFANT`,
        `EIP`,
        `INAMI`,
        `Résumé de l’entretien`,
        `Quelles sont les solutions les plus importantes pour vous actuellement ?`,
      ],
      [
        `VOTRE FEEDBACK NOUS INTÉRESSE !`,
      ],
      [
        `L’entretien était-il professionnelle ?`,
        `Avez-vous appris quelque chose aujourd’hui ?`,
        `Votre proche a-t-il bien fait de vous recommander à cet entretien ?`,
        `Aimeriez-vous aussi partager ces informations importantes avec vos proches ?`,
        `Les informations partagées étaient-elles intéressantes ?`,
        `1`,
        `2`,
        `3`,
        `4`,
        `5`,
      ],
      [
        `Ami(e)s proches?`,
        `Familles ?`,
        `Formulaire de recommandations :`,
        `Travailleurs : famille, ami(e)s, collègues et potentiels candidats?`,
      ],
      [
        `Je vous remercie pour votre attention !`,
      ],
    ],
  },
  {
    id: "traitement-objections",
    title: `Le traitement des objections`,
    slides: [
      [
        `FORMATION À L'ARGUMENTATION et le traitement des objections`,
        `Introduction`,
        `Ce n'est pas parce qu'un client vous donne une objection que vous devez conclure que la vente est perdue.`,
        `Au contraire : cela signifie que le client s'intéresse, teste vos réponses et cherche à être rassuré. Il veut acheter, mais a besoin de votre aide pour faire un choix.`,
        `Votre rôle : l'écouter, comprendre ce qui le bloque, et l'accompagner avec méthode.`,
        `Pour cela, voici les étapes essentielles à suivre pour transformer une objection en souscription.`,
      ],
      [
        `1. Identifier le type d'objection`,
        `Objection abstraite — floue, imprécise, difficile à traiter directement.`,
        `Exemple : « Je dois réfléchir. »`,
        `Ce type d'objection doit être clarifié.`,
        `Question à poser : « Si je peux me permettre… À quoi devez-vous réfléchir ? Je peux peut-être vous aider. »`,
        `Objection concrète — claire, précise, et donc traitable.`,
        `Exemple : « Je suis trop jeune. »`,
      ],
      [
        `2. Les étapes de traitement de l'objection`,
        `Une fois l'objection rendue concrète, voici les huit étapes à suivre :`,
      ],
      [
        `1. Le Silence`,
        `Prenez quelques secondes avant de répondre.`,
        `Cela montre que vous réfléchissez sérieusement à ce que dit le client.`,
      ],
      [
        `2. L'Empathie`,
        `Montrez que vous comprenez sa position.`,
        `« Je vous comprends, c'est une préoccupation légitime. »`,
      ],
      [
        `3. La Reformulation`,
        `Reformulez son objection pour valider votre compréhension.`,
        `« Donc, si je comprends bien, ce qui vous retient aujourd'hui c'est… »`,
      ],
      [
        `4. L'Isolation`,
        `Validez qu'il n'y a qu'un seul frein.`,
        `« Est-ce que c'est bien le seul point qui vous empêche d'avancer ? »`,
        `Si une autre objection apparaît, recommencez depuis l'étape 1.`,
      ],
      [
        `5. Le Pré-accord`,
        `Fixez un engagement conditionnel : « Donc si je vous apporte une solution à ce point précis, vous êtes prêt à démarrer aujourd'hui ? »`,
      ],
      [
        `6. L'Argumentation (interne)`,
        `C'est ici que vous préparez dans votre esprit la meilleure manière de présenter la solution.`,
        `Exemple si l'objection concerne l'âge du client :`,
        `Commencer jeune, c'est profiter pleinement des intérêts composés : une année d'attente peut représenter entre 3 000 et 5 000 € de manque à gagner à terme.`,
        `L'avantage fiscal : en commençant maintenant, vous commencez à déduire. Tout ce que vous ne déduisez pas, vous le donnez à l'État.`,
        `La protection : avec les assurances incluses, vous êtes couvert contre les accidents du quotidien. Ce sont souvent les jeunes actifs qui sont les plus exposés à ces risques.`,
        `Questions à se poser : Quelle est la meilleure alternative à proposer ? Quel est l'angle qui parlera le plus au client ? Quelle valeur concrète le client va-t-il retirer de la solution ?`,
        `L'objectif : préparer une réponse claire, simple et engageante.`,
      ],
      [
        `7. La Réponse (externe)`,
        `Utilisez la règle de l'alternative pour faciliter la décision sans mettre de pression.`,
        `Exemples pour closer :`,
        `« Souhaitez-vous démarrer avec la déduction fiscale à 315 € ou celle à 188 € ? »`,
        `« Vous préférez qu'on fixe le rendez-vous mardi ou mercredi avec l'expert ? »`,
        `« Vous seriez plus à l'aise avec un versement mensuel ou en une fois ? »`,
        `Vous guidez sans imposer, tout en provoquant l'engagement.`,
      ],
      [
        `8. La Conclusion`,
        `Une fois que le choix est affirmé, verrouillez la décision :`,
        `« Parfait, on peut compléter les documents ensemble maintenant ? »`,
      ],
      [
        `Conclusion`,
        `Un bon commercial ne fuit pas les objections : il les transforme en opportunités.`,
        `Souvenez-vous : l'objection n'est pas un refus.`,
        `C'est une demande de clarté, de confiance, de leadership.`,
        `Si vous appliquez ces étapes avec calme, empathie et méthode, vous signerez là où d'autres abandonnent.`,
      ],
    ],
  },
  {
    id: "prise-recommandation",
    title: `La prise de recommandation`,
    slides: [
      [
        `Les 14 étapes de la prise de recommandations`,
        `1. Libérer la pression.`,
        `2. Phrase d'introduction : « ah oui au fait, j'ai encore un petit rapport de service à la clientèle… »`,
        `3. Poser les 6 questions.`,
        `4. Rompre le contact visuel.`,
        `5. À qui pensez-vous ? (de manière claire : votre frère, sœur, collègue, ami du foot => induire)`,
        `6. Noter le plus rapidement possible quelque chose sur la feuille.`,
        `7. Donner un rythme : à qui d'autre ?`,
        `8. Technique Verti-Hori.`,
        `9. Laisser des interlignes (d'abord noter tout en haut, ensuite tout en bas, ensuite par-ci par-là).`,
        `10. Donner au client un objectif de recommandations à donner.`,
        `11. Utiliser la technique du répertoire téléphonique à la moindre hésitation : « Je connais une technique infaillible qui marche à tous les coups ! Lorsqu'on parcourt son répertoire téléphonique on voit toujours trois ou quatre personnes à qui on n'avait pas pensé ! » (Sortir son propre téléphone en parlant : verbal + non verbal)`,
        `12. Noter le numéro de téléphone du lien le plus proche en commençant par 04… et ensuite prendre tous les numéros.`,
        `13. Compléter les informations complémentaires.`,
        `14. Envoyer un sms avec le client afin d'immuniser les recommandations.`,
      ],
      [
        `Les 6 questions de la cascade de OUI`,
        `1. Concernant notre entretien, y avez-vous trouvé de l'intérêt ?`,
        `2. Avez-vous été conseillé de manière professionnelle ?`,
        `3. Avez-vous appris quelque chose ?`,
        `4. Pensez-vous que tout le monde devrait avoir accès à ces informations aussi nécessaires de nos jours ?`,
        `5. Recommanderiez-vous ce service ?`,
        `6. Pour quelles raisons ?`,
      ],
      [
        `Les 3 étapes lors d'une objection sur la prise de recommandations`,
        `1. Accueillir l'objection de manière positive.`,
        `2. Aller dans le sens du client (empathie).`,
        `3. Répondre positivement en rappelant pourquoi le précédent l'a recommandé, et ensuite rebondir sur « à qui pensez-vous ? » et rompre le contact visuel + bic sur feuille !`,
      ],
      [
        `« Je veux d'abord… »`,
        `1. C'est normal…`,
        `2. C'est exactement ce que j'ai fait avec le précédent… (votre ami)`,
        `3. D'ailleurs c'est exactement ce que je vais vous demander de faire à la fin de notre exercice (via sms ou appel)`,
        `4. Ensuite rebondir sur « à qui pensez-vous ? » et rompre le contact visuel + bic sur feuille !`,
      ],
      [
        `Argumentation — Situation I`,
        `Client : « Je veux d'abord en parler avec la personne que je vais vous recommander ! »`,
        `Collaborateur : Génial, c'est une très bonne idée car c'est exactement de cette manière-là que j'aime procéder. Comme je vous l'ai dit, je fonctionne uniquement sur base de recommandations !`,
        `Je dois vous avouer que cela me mettrait mal à l'aise de savoir que vous allez travailler à ma place, sachant qu'il est fort possible que vous ne soyez pas en mesure de répondre à toutes les questions ou même expliquer la chose correctement.`,
        `C'est pourquoi je vous propose que l'on voie ensemble qui serait recommandable, et sur base de cela je vous expliquerai comment nous pourrons procéder afin que vous puissiez en parler avant.`,
      ],
      [
        `Argumentation — Situation II`,
        `Client : « Je ne sais pas si ça va les intéresser ? »`,
        `Collaborateur : Et bien écoutez, je ne sais pas non plus ! Il est difficile de s'intéresser à une information que l'on n'a pas encore reçue. Et c'est justement mon rôle : aujourd'hui, vous m'avez dit que…`,
        `— Cela était intéressant, que l'analyse a été faite de façon professionnelle, que tout le monde devrait recevoir cette information, que vous avez appris quelque chose, et même que vous recommanderiez ce service.`,
        `De nos jours, connaissez-vous une personne qui ne serait pas intéressée de payer moins d'impôts ? Client : Non.`,
        `Collaborateur : On est d'accord ! Alors, à qui souhaitez-vous donner la possibilité de recevoir ces informations gratuites qui vont, grâce à vous, leur permettre de payer moins d'impôts ?`,
      ],
      [
        `Argumentation — Situation III`,
        `Client : « Je ne préfère pas donner de numéro de téléphone ! »`,
        `Collaborateur : Je suis étonné, car c'est la première fois que j'entends cela. En général, j'ai pour habitude que les personnes me recommandent entre 15 et 20 noms, parfois plus ! Est-ce que le problème c'est moi ? Ai-je mal fait mon travail ?`,
        `Client : (peu importe la réponse du client)`,
        `Collaborateur : Dans ce cas, quelle est la véritable raison ? Vous m'avez dit que vous étiez ok pour recommander mon service !`,
        `NB : le client va s'exprimer et donc on retombe sur une des objections ci-dessus.`,
        `Le véritable secret lors de la prise de recommandations : simplement avoir confiance en vous !`,
      ],
    ],
  },
];
