-- ============================================================================
-- Bâtisseur — migration : rattrapage historique 2026 depuis les relevés OVB
-- Willemot réels (janvier à juillet 2026, 179 contrats).
-- À coller dans Supabase Dashboard → SQL Editor → New query → Run, APRÈS
-- avoir exécuté 010_ovb_import.sql.
-- ============================================================================
-- Ne supprime et ne duplique rien : les contrats déjà présents dans le CRM
-- (retrouvés par collaborateur + client + montant + unités) sont juste
-- recalés à leur vrai mois ; seuls les contrats vraiment absents sont créés.
-- ============================================================================

select public.import_ovb_contracts(
$ovb$
[
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Jackline Ansah","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-01"},
{"collaborateur":"Boateng, Frank","client":"Dheur, Jason","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-01"},
{"collaborateur":"Boateng, Frank","client":"Massillon, Valentin","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bolou, Yann Raphaël","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bolou, Yann Raphaël","partenaire":"P&V Belgique","produit":"NZMEER5JR","montant":705.72,"unites":20.47,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Da Fonseca Benjamin, Vanuza","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"De Souza, Jacqueline","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.36,"unites":64.70,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kalisa, Daniel","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kalisa, Daniel","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kalisa, Daniel","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kalisa, David","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kalisa, David","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kalisa, David","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Mutsinzi Mutunzi, Darcy","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-01"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Mutsinzi Mutunzi, Darcy","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-01"},
{"collaborateur":"Forkuo, Justice","client":"Atikey, Komi","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1260.00,"unites":50.40,"mois":"2026-01"},
{"collaborateur":"Lutete Bobela, Armed","client":"Lutete Madala, Léonce","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-01"},

{"collaborateur":"Addai, Michael","client":"Mokeli, Julie","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-02"},
{"collaborateur":"Addai, Michael","client":"Mokeli, Julie","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-02"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Caiquo, Bobby","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.12,"unites":32.35,"mois":"2026-02"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Caiquo, Bobby","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.12,"unites":32.35,"mois":"2026-02"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Yossa Noubissie, Nancy","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-02"},
{"collaborateur":"Boateng, Frank","client":"Adamus, Elodie Marie I","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-02"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Camara, Mohamed","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":997.56,"unites":53.20,"mois":"2026-02"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Eyang-Nguema Medja, Gisela","partenaire":"P&V Belgique","produit":"NZMEER5JR","montant":1764.72,"unites":51.18,"mois":"2026-02"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kaba, Fatou","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-02"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Mballa, Emmanuel","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":997.56,"unites":53.20,"mois":"2026-02"},
{"collaborateur":"Forkuo, Justice","client":"Lago, Fabrice","partenaire":"P&V Belgique","produit":"AVVIVIUMVAPZ23BE","montant":3778.08,"unites":177.57,"mois":"2026-02"},
{"collaborateur":"Forkuo, Justice","client":"Lago, Fabrice","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-02"},
{"collaborateur":"Forkuo, Justice","client":"Lago, Fabrice","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1710.00,"unites":91.19,"mois":"2026-02"},
{"collaborateur":"Forkuo, Justice","client":"Lago, Marie Jeanne C (Claude)","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":748.08,"unites":29.92,"mois":"2026-02"},

{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Amenyo, Kossi Benjamin","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-03"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Amenyo, Kossi Benjamin","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-03"},
{"collaborateur":"Boateng, Frank","client":"Dzisiak, Céline","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-03"},
{"collaborateur":"Boateng, Frank","client":"Dzisiak, Céline","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, Kendra","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1764.84,"unites":97.07,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, Kendra","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, Kendra","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, Kendra","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Amah, Varela Magnim","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bolou, Yann Raphaël","partenaire":"P&V Belgique","produit":"NZMEER5JR","montant":1176.36,"unites":34.11,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Van Weynsberghe, Dorcas Ekua","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.48,"unites":64.71,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Van Weynsberghe, Dorcas Ekua","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1296.72,"unites":51.87,"mois":"2026-03"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Van Weynsberghe, Dorcas Ekua","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-03"},
{"collaborateur":"Forkuo, Justice","client":"Dango Nadey, Koudirath","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.60,"unites":64.71,"mois":"2026-03"},
{"collaborateur":"Forkuo, Justice","client":"Dango Nadey, Koudirath","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.48,"unites":64.71,"mois":"2026-03"},
{"collaborateur":"Forkuo, Justice","client":"Dango Nadey, Koudirath","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.36,"unites":64.70,"mois":"2026-03"},
{"collaborateur":"Lutete Bobela, Armed","client":"Filieux, Béatrice Ghislaine","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-03"},
{"collaborateur":"Lutete Bobela, Armed","client":"Rookx, Eva","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-03"},

{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Addo, Simeon Opoku","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-04"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boateng, Regina","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":2353.08,"unites":129.42,"mois":"2026-04"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Bonsu, Felix Mensah","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-04"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Bonsu, Felix Mensah","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bolou, Yann Raphaël","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nkangala, Fortuné","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nkangala, Fortuné","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Yankey, Jusinta","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.24,"unites":32.35,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Yankey, Jusinta","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.24,"unites":32.35,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Yankey, Jusinta","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.24,"unites":32.35,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Yankey, Jusinta","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-04"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Yankey, Jusinta","partenaire":"DELA Belgique","produit":"DELANLZ","montant":20000.00,"unites":100.00,"mois":"2026-04"},
{"collaborateur":"Forkuo, Justice","client":"Atila, Salomey","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1296.72,"unites":51.87,"mois":"2026-04"},
{"collaborateur":"Forkuo, Justice","client":"Atila, Salomey","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-04"},
{"collaborateur":"Forkuo, Justice","client":"Lambert, Gilbert Junior T","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-04"},
{"collaborateur":"Forkuo, Justice","client":"Lambert, Gilbert Junior T","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-04"},

{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Darkwaa, Patricia","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-05"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Kahigo, Justy","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-05"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Kahigo, Justy","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-05"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Manu, George Peprah","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-05"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Owusu, Ernestina Opokua","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-05"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Hadji, Landrine","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.24,"unites":32.35,"mois":"2026-05"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kalam, Worou-Nadjim","partenaire":"P&V Belgique","produit":"NZMEER5JR","montant":588.12,"unites":17.06,"mois":"2026-05"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Kiala, Kevin","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":705.72,"unites":38.81,"mois":"2026-05"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nkanda, Jordan","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-05"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nkanda, Jordan","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-05"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nkangala, Fortuné","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-05"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Uwituse, Delphine","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Amenyo, Akosuavi Madeleine","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":823.56,"unites":45.30,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Amenyo, Akosuavi Madeleine","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Amenyo, Akosuavi Madeleine","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Amenyo, Akosuavi Madeleine","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Asante, Angelina Nelly","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1710.00,"unites":91.19,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Asante, Angelina Nelly","partenaire":"P&V Belgique","produit":"REVENUS","montant":1666.92,"unites":75.01,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Boateng, Bright","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Boateng, Joyce","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Diamonde, Mohammed Lamine","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Djomessin, Alvine Mireille","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.48,"unites":64.71,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Djomessin, Alvine Mireille","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.12,"unites":32.35,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Djomessin, Alvine Mireille","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Djomessin, Alvine Mireille","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Djomessin, Alvine Mireille","partenaire":"DELA Belgique","produit":"DELA2","montant":0.00,"unites":0.00,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Kabagwira, Marceline","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":2736.00,"unites":109.44,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Maiga, Ibrahim Adam","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1197.00,"unites":47.88,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Maiga, Ibrahim Adam","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1197.00,"unites":47.88,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Mensah, Samuel","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1296.72,"unites":51.87,"mois":"2026-05"},
{"collaborateur":"Forkuo, Justice","client":"Mensah, Samuel","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1710.00,"unites":91.19,"mois":"2026-05"},

{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Agyei, Antwi","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Ahadjie, Laurene","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Ahadjie, Laurene","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Amoako, Kwadwo","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Appiah Dadey, Portia","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1470.48,"unites":80.88,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Appiah Dadey, Portia","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1197.00,"unites":47.88,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Asoka, Yaa","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Baafour Awuah, Nana Akwasi","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Caiquo, Bobby","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":2565.00,"unites":136.79,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Dwomoh, Sylvia","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Gagalo, Afi","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Lawson, Gabriel Appiahene","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Nyandja, Sambel Gregory","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Serwaah, Ataa","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Serwaah, Atta","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Serwaah, Atta","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Tchummamo Fokam, Michel","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Tchummamo Fokam, Michel","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Tchummamo Fokam, Michel","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Yossa Noubissie, Nancy","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Yossa Noubissie, Nancy","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Yossa Noubissie, Nancy","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, James","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.48,"unites":64.71,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, James","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, James","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, Maxwell","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Adjaye, Maxwell","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Anane, Victoria Yaa","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.12,"unites":32.35,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Anane, Victoria Yaa","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Dagadou, Tsatsu Sessi Y","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Dagadou, Tsatsu Sessi Y","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Daniel, Rebecca","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nkanda, Jordan","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nyandja, Sambel Gregory","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Nyandja, Sambel Gregory","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Peire, Nalane","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Peire, Nalane","partenaire":"DELA Belgique","produit":"DELANLZ","montant":20000.00,"unites":100.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Uwituse, Delphine","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1000.08,"unites":55.00,"mois":"2026-06"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Uwituse, Delphine","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Adjaye, Maxwell","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.24,"unites":32.35,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Adu Appiah, Sylvester","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Appiah Dadey, Portia","partenaire":"P&V Belgique","produit":"AVVIVIUM21BE","montant":1470.36,"unites":55.87,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Appiah Dadey, Portia","partenaire":"P&V Belgique","produit":"AVVIVIUM21BE","montant":1470.36,"unites":55.87,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Appiah Dadey, Portia","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1470.48,"unites":80.88,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Appiah Dadey, Portia","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Appiah Dadey, Portia","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Frimpong, Mavis Kyeremaa","partenaire":"P&V Belgique","produit":"AVVIVIUMVAPZ23BE","montant":2855.88,"unites":134.23,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Hassan, Adia Hassan","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Hassan, Adia Hassan","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Hassan, Adia Hassan","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Hassan, Adia Hassan","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Hassan, Amini Hassan","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Jiongo Nguefack, Elionore","partenaire":"P&V Belgique","produit":"AVVIVIUMVAPZ23BE","montant":1419.36,"unites":66.71,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Kanga, Christian","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Mukeshimana, Hamida","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":1496.28,"unites":59.85,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Mukeshimana, Hamida","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":684.00,"unites":27.36,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Mukeshimana, Hamida","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":684.00,"unites":36.48,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Wiafe, Kwame","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":684.00,"unites":27.36,"mois":"2026-06"},
{"collaborateur":"Forkuo, Justice","client":"Wiafe, Kwame","partenaire":"AXA Belgium","produit":"AXAPENS10","montant":741.00,"unites":29.64,"mois":"2026-06"},

{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Mavis","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":3529.44,"unites":194.12,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Mavis","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Mavis","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Mavis","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Moses Amoako","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":3420.00,"unites":182.39,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Moses Amoako","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Moses Amoako","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Boakye, Moses Amoako","partenaire":"DELA Belgique","produit":"DELANLZ","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Dwomoh, Sylvia","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":705.84,"unites":38.82,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Fowe, Rose Charnelle","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Fowe, Rose Charnelle","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"Fowe, Rose Charnelle","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"N'Guessan, Ashley Vanessa","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"N'Guessan, Kouamé Hervé","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"N'Guessan, Kouamé Hervé","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":855.00,"unites":45.60,"mois":"2026-07"},
{"collaborateur":"Baafour Awuah, Nana Akwasi","client":"N'Guessan, Pauline Laëtitia","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Amaglo, Amah Daline L","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bagueya, Mohamed","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.48,"unites":64.71,"mois":"2026-07"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bagueya, Mohamed","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":588.24,"unites":32.35,"mois":"2026-07"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bagueya, Mohamed","partenaire":"AXA Belgium","produit":"AXAPENS20","montant":1496.28,"unites":79.80,"mois":"2026-07"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Bagueya, Mohamed","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Sylla, Marie","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1176.48,"unites":64.71,"mois":"2026-07"},
{"collaborateur":"Ettitchi, Kacou Loïc Samuel","client":"Sylla, Marie","partenaire":"P&V Belgique","produit":"AVVIVIUM23BE","montant":1764.72,"unites":97.06,"mois":"2026-07"},
{"collaborateur":"Forkuo, Justice","client":"Fabry, Dominique Marie","partenaire":"DELA Belgique","produit":"DELA2","montant":10000.00,"unites":60.00,"mois":"2026-07"}
]
$ovb$::jsonb,
true
);
